### ISSUE TITLE
Where do we enter the OpenAI API key?

### ISSUE THREAD

**Issue by lundeen-bryan** [bramses/comde#1]
I have a python file in a directory, i used COMDE on it and then got the error "Error appending to COMDE.md, see log" but I placed a COMDE.md file in the same directory as the python file. Where else would I place that COMDE.md file?

**Comment by bramses** [comment]
I believe COMDE.md has to sit in the root directory of the project to be appended correctly.

P.S. if you are using this project you should look into Stenography instead (https://stenography.dev). I built it as the spiritual successor of COMDE and it's like 1 million times better thought out/implemented

**Comment by lundeen-bryan** [comment]
Thanks, looks like stenography is what I was looking for - commenting all the functions in the file. Thank you!

**Comment by bramses** [comment]
You're welcome!
